version: "3"
services:
  
  mysql:
    container_name: mysql-db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root2021
      - MYSQL_DATABASE=timesheetspring
    
    ports:
      - 3306:3306
    
    
  Timesheet:
    container_name: timesheet
    ports:
      - 8082:8082
    environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/timesheetspring?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
     - SPRING_DATASOURCE_USERNAME=root
     - DATABASE_USER=root
     - SPRING_DATASOURCE_PASSWORD=root2021
     - DATABASE_NAME=timesheetspring
     - DATABASE_PORT=3306
    image: "199508055180/test"
    hostname: timesheet
    depends_on:
      - mysql